apiVersion: v1
kind: Pod
metadata:
  name: demosecret-maleka
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: hideme-malika
            key: dbhost
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: hideme-malika
            key: username
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            name: hideme-malika
            key: password
  restartPolicy: Never
