apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"myapp","type":"front-end"},"name":"nginx-app","namespace":"malika"},"spec":{"replicas":1,"selector":{"matchLabels":{"type":"front-end"}},"template":{"metadata":{"labels":{"app":"myapp","type":"front-end"},"name":"nginx-app"},"spec":{"containers":[{"image":"ngixn:stable","name":"webapp"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: myapp
    type: front-end
  name: nginx-app
  selfLink: /apis/apps/v1/namespaces/malika/deployments/nginx-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      type: front-end
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
        type: front-end
      name: nginx-app
    spec:
      containers:
      - image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
