apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      volumeMounts:
      - name: config
        mountPath: "/etc/nginx/nginx.conf"
        subPath: "nginx.conf"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: nginx-config
        items:
        - key: "nginx.conf"
          path: "nginx.conf"
  
