apiVersion: v1
kind: Secret
metadata:
  name: hideme-malika
type: Opaque
data:
  dbhost: ZGItZGV2LmN5dXJnemVjcmg3ei51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  username: cm9vdA==
  password: NEtpQVVQZ1ZyWHlWbVZkUA==
