apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  label:
    app: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
