apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  selector:
    app: voting-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
