apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: voting-app
      labels:
        app: voting-app
    spec:
      containers:
      - name: python
        image: mshaibek/voting-app_vote:1.0
  replicas: 1
  selector:
    matchLabels:
      app: voting-app 
